---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: openmrs-Deployment
spec: 
  minReadySeconds: 2
  replicas: 2
  selector:
    app: openmrs
    ver: 2.4 
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  Template: 
    metadata:
      labels:
        app: openmrs
        ver: 2.4
    spec:
      containers:
        - name: openmrs
          image: shaikkhajaibrahim/openmrs-core:2.4.0
      ports:
        - containerPort: 8080
          protocol: TCP 