<<<<<<< HEAD
---
apiVersion: v1
kind: Pod
metadata:
  name: openmrs
  label: 
    app: openmrs
    version: 2.0
spec:
  containers:
    - name: openmrs
      image: 
      ports:
        - containerPort: 8080
=======
---
apiVersion: v1
kind: Pod
metadata:
  name: openmrs
  label: 
    app: openmrs
    version: 2.0
spec:
  containers:
    - name: openmrs
      image: 
      ports:
        - containerPort: 8080
>>>>>>> 1faeaae778ff098ff6446d92f8b59f9e9e534434
          protocol: TCP 